apiVersion: v1
kind: ConfigMap
metadata:
  name: unit-converter-config
  namespace: default
data:
  CONVERSION_SERVICE_URL: "http://conversion-service:8080"
  HISTORY_SERVICE_URL: "http://history-service:8081"