apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: conversion-service-hpa
  namespace: default
spec:
  # Deployment to scale
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: conversion-service

  # Min and max pods
  minReplicas: 2
  maxReplicas: 5

  metrics:
    # CPU-based scaling
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70